/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jmeter.plugin.hangqing;

public final class EesEqsLogLevel {
  public final static EesEqsLogLevel QUOTE_LOG_LV_DEBUG = new EesEqsLogLevel("QUOTE_LOG_LV_DEBUG", shenglihangqingJNI.QUOTE_LOG_LV_DEBUG_get());
  public final static EesEqsLogLevel QUOTE_LOG_LV_INFO = new EesEqsLogLevel("QUOTE_LOG_LV_INFO", shenglihangqingJNI.QUOTE_LOG_LV_INFO_get());
  public final static EesEqsLogLevel QUOTE_LOG_LV_WARN = new EesEqsLogLevel("QUOTE_LOG_LV_WARN", shenglihangqingJNI.QUOTE_LOG_LV_WARN_get());
  public final static EesEqsLogLevel QUOTE_LOG_LV_ERROR = new EesEqsLogLevel("QUOTE_LOG_LV_ERROR", shenglihangqingJNI.QUOTE_LOG_LV_ERROR_get());
  public final static EesEqsLogLevel QUOTE_LOG_LV_FATAL = new EesEqsLogLevel("QUOTE_LOG_LV_FATAL", shenglihangqingJNI.QUOTE_LOG_LV_FATAL_get());
  public final static EesEqsLogLevel QUOTE_LOG_LV_USER = new EesEqsLogLevel("QUOTE_LOG_LV_USER", shenglihangqingJNI.QUOTE_LOG_LV_USER_get());
  public final static EesEqsLogLevel QUOTE_LOG_LV_END = new EesEqsLogLevel("QUOTE_LOG_LV_END");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static EesEqsLogLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + EesEqsLogLevel.class + " with value " + swigValue);
  }

  private EesEqsLogLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private EesEqsLogLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private EesEqsLogLevel(String swigName, EesEqsLogLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static EesEqsLogLevel[] swigValues = { QUOTE_LOG_LV_DEBUG, QUOTE_LOG_LV_INFO, QUOTE_LOG_LV_WARN, QUOTE_LOG_LV_ERROR, QUOTE_LOG_LV_FATAL, QUOTE_LOG_LV_USER, QUOTE_LOG_LV_END };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

