/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jmeter.plugin.hangqing;

public class EESMarketDepthQuoteData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EESMarketDepthQuoteData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EESMarketDepthQuoteData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EESMarketDepthQuoteData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        shenglihangqingJNI.delete_EESMarketDepthQuoteData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradingDay(String value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_TradingDay_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_ExchangeID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_ExchangeInstID_get(swigCPtr, this);
  }

  public void setLastPrice(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_LastPrice_set(swigCPtr, this, value);
  }

  public double getLastPrice() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_LastPrice_get(swigCPtr, this);
  }

  public void setPreSettlementPrice(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_PreSettlementPrice_set(swigCPtr, this, value);
  }

  public double getPreSettlementPrice() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_PreSettlementPrice_get(swigCPtr, this);
  }

  public void setPreClosePrice(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_PreClosePrice_set(swigCPtr, this, value);
  }

  public double getPreClosePrice() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_PreClosePrice_get(swigCPtr, this);
  }

  public void setPreOpenInterest(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_PreOpenInterest_set(swigCPtr, this, value);
  }

  public double getPreOpenInterest() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_PreOpenInterest_get(swigCPtr, this);
  }

  public void setOpenPrice(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_OpenPrice_set(swigCPtr, this, value);
  }

  public double getOpenPrice() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_OpenPrice_get(swigCPtr, this);
  }

  public void setHighestPrice(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_HighestPrice_set(swigCPtr, this, value);
  }

  public double getHighestPrice() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_HighestPrice_get(swigCPtr, this);
  }

  public void setLowestPrice(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_LowestPrice_set(swigCPtr, this, value);
  }

  public double getLowestPrice() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_LowestPrice_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_Volume_get(swigCPtr, this);
  }

  public void setTurnover(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_Turnover_set(swigCPtr, this, value);
  }

  public double getTurnover() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_Turnover_get(swigCPtr, this);
  }

  public void setOpenInterest(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_OpenInterest_set(swigCPtr, this, value);
  }

  public double getOpenInterest() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_OpenInterest_get(swigCPtr, this);
  }

  public void setClosePrice(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_ClosePrice_set(swigCPtr, this, value);
  }

  public double getClosePrice() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_ClosePrice_get(swigCPtr, this);
  }

  public void setSettlementPrice(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_SettlementPrice_set(swigCPtr, this, value);
  }

  public double getSettlementPrice() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_SettlementPrice_get(swigCPtr, this);
  }

  public void setUpperLimitPrice(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_UpperLimitPrice_set(swigCPtr, this, value);
  }

  public double getUpperLimitPrice() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_UpperLimitPrice_get(swigCPtr, this);
  }

  public void setLowerLimitPrice(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_LowerLimitPrice_set(swigCPtr, this, value);
  }

  public double getLowerLimitPrice() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_LowerLimitPrice_get(swigCPtr, this);
  }

  public void setPreDelta(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_PreDelta_set(swigCPtr, this, value);
  }

  public double getPreDelta() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_PreDelta_get(swigCPtr, this);
  }

  public void setCurrDelta(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_CurrDelta_set(swigCPtr, this, value);
  }

  public double getCurrDelta() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_CurrDelta_get(swigCPtr, this);
  }

  public void setUpdateTime(String value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_UpdateTime_set(swigCPtr, this, value);
  }

  public String getUpdateTime() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_UpdateTime_get(swigCPtr, this);
  }

  public void setUpdateMillisec(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_UpdateMillisec_set(swigCPtr, this, value);
  }

  public int getUpdateMillisec() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_UpdateMillisec_get(swigCPtr, this);
  }

  public void setBidPrice1(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_BidPrice1_set(swigCPtr, this, value);
  }

  public double getBidPrice1() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_BidPrice1_get(swigCPtr, this);
  }

  public void setBidVolume1(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_BidVolume1_set(swigCPtr, this, value);
  }

  public int getBidVolume1() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_BidVolume1_get(swigCPtr, this);
  }

  public void setAskPrice1(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_AskPrice1_set(swigCPtr, this, value);
  }

  public double getAskPrice1() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_AskPrice1_get(swigCPtr, this);
  }

  public void setAskVolume1(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_AskVolume1_set(swigCPtr, this, value);
  }

  public int getAskVolume1() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_AskVolume1_get(swigCPtr, this);
  }

  public void setBidPrice2(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_BidPrice2_set(swigCPtr, this, value);
  }

  public double getBidPrice2() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_BidPrice2_get(swigCPtr, this);
  }

  public void setBidVolume2(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_BidVolume2_set(swigCPtr, this, value);
  }

  public int getBidVolume2() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_BidVolume2_get(swigCPtr, this);
  }

  public void setAskPrice2(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_AskPrice2_set(swigCPtr, this, value);
  }

  public double getAskPrice2() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_AskPrice2_get(swigCPtr, this);
  }

  public void setAskVolume2(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_AskVolume2_set(swigCPtr, this, value);
  }

  public int getAskVolume2() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_AskVolume2_get(swigCPtr, this);
  }

  public void setBidPrice3(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_BidPrice3_set(swigCPtr, this, value);
  }

  public double getBidPrice3() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_BidPrice3_get(swigCPtr, this);
  }

  public void setBidVolume3(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_BidVolume3_set(swigCPtr, this, value);
  }

  public int getBidVolume3() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_BidVolume3_get(swigCPtr, this);
  }

  public void setAskPrice3(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_AskPrice3_set(swigCPtr, this, value);
  }

  public double getAskPrice3() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_AskPrice3_get(swigCPtr, this);
  }

  public void setAskVolume3(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_AskVolume3_set(swigCPtr, this, value);
  }

  public int getAskVolume3() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_AskVolume3_get(swigCPtr, this);
  }

  public void setBidPrice4(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_BidPrice4_set(swigCPtr, this, value);
  }

  public double getBidPrice4() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_BidPrice4_get(swigCPtr, this);
  }

  public void setBidVolume4(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_BidVolume4_set(swigCPtr, this, value);
  }

  public int getBidVolume4() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_BidVolume4_get(swigCPtr, this);
  }

  public void setAskPrice4(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_AskPrice4_set(swigCPtr, this, value);
  }

  public double getAskPrice4() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_AskPrice4_get(swigCPtr, this);
  }

  public void setAskVolume4(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_AskVolume4_set(swigCPtr, this, value);
  }

  public int getAskVolume4() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_AskVolume4_get(swigCPtr, this);
  }

  public void setBidPrice5(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_BidPrice5_set(swigCPtr, this, value);
  }

  public double getBidPrice5() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_BidPrice5_get(swigCPtr, this);
  }

  public void setBidVolume5(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_BidVolume5_set(swigCPtr, this, value);
  }

  public int getBidVolume5() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_BidVolume5_get(swigCPtr, this);
  }

  public void setAskPrice5(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_AskPrice5_set(swigCPtr, this, value);
  }

  public double getAskPrice5() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_AskPrice5_get(swigCPtr, this);
  }

  public void setAskVolume5(int value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_AskVolume5_set(swigCPtr, this, value);
  }

  public int getAskVolume5() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_AskVolume5_get(swigCPtr, this);
  }

  public void setAveragePrice(double value) {
    shenglihangqingJNI.EESMarketDepthQuoteData_AveragePrice_set(swigCPtr, this, value);
  }

  public double getAveragePrice() {
    return shenglihangqingJNI.EESMarketDepthQuoteData_AveragePrice_get(swigCPtr, this);
  }

  public EESMarketDepthQuoteData() {
    this(shenglihangqingJNI.new_EESMarketDepthQuoteData(), true);
  }

}
