/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jmeter.plugin.hangqing;

public class EqsTcpInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EqsTcpInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EqsTcpInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(EqsTcpInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        shenglihangqingJNI.delete_EqsTcpInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EqsTcpInfo() {
    this(shenglihangqingJNI.new_EqsTcpInfo(), true);
  }

  public void setM_eqsId(String value) {
    shenglihangqingJNI.EqsTcpInfo_m_eqsId_set(swigCPtr, this, value);
  }

  public String getM_eqsId() {
    return shenglihangqingJNI.EqsTcpInfo_m_eqsId_get(swigCPtr, this);
  }

  public void setM_eqsIp(String value) {
    shenglihangqingJNI.EqsTcpInfo_m_eqsIp_set(swigCPtr, this, value);
  }

  public String getM_eqsIp() {
    return shenglihangqingJNI.EqsTcpInfo_m_eqsIp_get(swigCPtr, this);
  }

  public void setM_eqsPort(int value) {
    shenglihangqingJNI.EqsTcpInfo_m_eqsPort_set(swigCPtr, this, value);
  }

  public int getM_eqsPort() {
    return shenglihangqingJNI.EqsTcpInfo_m_eqsPort_get(swigCPtr, this);
  }

}
