/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jmeter.plugin.hangqing;

public interface shenglihangqingConstants {
  public final static int EES_EQS_ID_LEN = shenglihangqingJNI.EES_EQS_ID_LEN_get();
  public final static int EES_EQS_USER_ID_LEN = shenglihangqingJNI.EES_EQS_USER_ID_LEN_get();
  public final static int EES_EQS_PASSWORD_LEN = shenglihangqingJNI.EES_EQS_PASSWORD_LEN_get();
  public final static String EES_QUOTE_DLL_NAME = shenglihangqingJNI.EES_QUOTE_DLL_NAME_get();
  public final static String CREATE_EES_QUOTE_API_NAME = shenglihangqingJNI.CREATE_EES_QUOTE_API_NAME_get();
  public final static String DESTROY_EES_QUOTE_API_NAME = shenglihangqingJNI.DESTROY_EES_QUOTE_API_NAME_get();
}
