/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jmeter.plugin.hangqing;

public class shenglihangqing implements shenglihangqingConstants {
  public static EESQuoteApi CreateEESQuoteApi() {
    long cPtr = shenglihangqingJNI.CreateEESQuoteApi();
    return (cPtr == 0) ? null : new EESQuoteApi(cPtr, false);
  }

  public static void DestroyEESQuoteApi(EESQuoteApi pEESQuoteApi) {
    shenglihangqingJNI.DestroyEESQuoteApi(EESQuoteApi.getCPtr(pEESQuoteApi), pEESQuoteApi);
  }

}
