/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jmeter.plugin.hangqing;

public class shenglihangqingJNI {
  public final static native long CreateEESQuoteApi();
  public final static native void DestroyEESQuoteApi(long jarg1, EESQuoteApi jarg1_);
  public final static native int EES_EQS_ID_LEN_get();
  public final static native int EES_EQS_USER_ID_LEN_get();
  public final static native int EES_EQS_PASSWORD_LEN_get();
  public final static native int EQS_INVALID_TYPE_get();
  public final static native int QUOTE_LOG_LV_DEBUG_get();
  public final static native int QUOTE_LOG_LV_INFO_get();
  public final static native int QUOTE_LOG_LV_WARN_get();
  public final static native int QUOTE_LOG_LV_ERROR_get();
  public final static native int QUOTE_LOG_LV_FATAL_get();
  public final static native int QUOTE_LOG_LV_USER_get();
  public final static native void EqsMulticastInfo_m_mcIp_set(long jarg1, EqsMulticastInfo jarg1_, String jarg2);
  public final static native String EqsMulticastInfo_m_mcIp_get(long jarg1, EqsMulticastInfo jarg1_);
  public final static native void EqsMulticastInfo_m_mcPort_set(long jarg1, EqsMulticastInfo jarg1_, int jarg2);
  public final static native int EqsMulticastInfo_m_mcPort_get(long jarg1, EqsMulticastInfo jarg1_);
  public final static native void EqsMulticastInfo_m_mcLoacalIp_set(long jarg1, EqsMulticastInfo jarg1_, String jarg2);
  public final static native String EqsMulticastInfo_m_mcLoacalIp_get(long jarg1, EqsMulticastInfo jarg1_);
  public final static native void EqsMulticastInfo_m_mcLocalPort_set(long jarg1, EqsMulticastInfo jarg1_, int jarg2);
  public final static native int EqsMulticastInfo_m_mcLocalPort_get(long jarg1, EqsMulticastInfo jarg1_);
  public final static native void EqsMulticastInfo_m_exchangeId_set(long jarg1, EqsMulticastInfo jarg1_, String jarg2);
  public final static native String EqsMulticastInfo_m_exchangeId_get(long jarg1, EqsMulticastInfo jarg1_);
  public final static native long new_EqsMulticastInfo();
  public final static native void delete_EqsMulticastInfo(long jarg1);
  public final static native long new_EqsTcpInfo();
  public final static native void EqsTcpInfo_m_eqsId_set(long jarg1, EqsTcpInfo jarg1_, String jarg2);
  public final static native String EqsTcpInfo_m_eqsId_get(long jarg1, EqsTcpInfo jarg1_);
  public final static native void EqsTcpInfo_m_eqsIp_set(long jarg1, EqsTcpInfo jarg1_, String jarg2);
  public final static native String EqsTcpInfo_m_eqsIp_get(long jarg1, EqsTcpInfo jarg1_);
  public final static native void EqsTcpInfo_m_eqsPort_set(long jarg1, EqsTcpInfo jarg1_, int jarg2);
  public final static native int EqsTcpInfo_m_eqsPort_get(long jarg1, EqsTcpInfo jarg1_);
  public final static native void delete_EqsTcpInfo(long jarg1);
  public final static native long new_EqsLoginParam();
  public final static native void EqsLoginParam_m_loginId_set(long jarg1, EqsLoginParam jarg1_, String jarg2);
  public final static native String EqsLoginParam_m_loginId_get(long jarg1, EqsLoginParam jarg1_);
  public final static native void EqsLoginParam_m_password_set(long jarg1, EqsLoginParam jarg1_, String jarg2);
  public final static native String EqsLoginParam_m_password_get(long jarg1, EqsLoginParam jarg1_);
  public final static native void delete_EqsLoginParam(long jarg1);
  public final static native void EESMarketDepthQuoteData_TradingDay_set(long jarg1, EESMarketDepthQuoteData jarg1_, String jarg2);
  public final static native String EESMarketDepthQuoteData_TradingDay_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_InstrumentID_set(long jarg1, EESMarketDepthQuoteData jarg1_, String jarg2);
  public final static native String EESMarketDepthQuoteData_InstrumentID_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_ExchangeID_set(long jarg1, EESMarketDepthQuoteData jarg1_, String jarg2);
  public final static native String EESMarketDepthQuoteData_ExchangeID_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_ExchangeInstID_set(long jarg1, EESMarketDepthQuoteData jarg1_, String jarg2);
  public final static native String EESMarketDepthQuoteData_ExchangeInstID_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_LastPrice_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_LastPrice_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_PreSettlementPrice_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_PreSettlementPrice_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_PreClosePrice_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_PreClosePrice_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_PreOpenInterest_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_PreOpenInterest_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_OpenPrice_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_OpenPrice_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_HighestPrice_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_HighestPrice_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_LowestPrice_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_LowestPrice_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_Volume_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_Volume_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_Turnover_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_Turnover_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_OpenInterest_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_OpenInterest_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_ClosePrice_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_ClosePrice_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_SettlementPrice_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_SettlementPrice_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_UpperLimitPrice_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_UpperLimitPrice_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_LowerLimitPrice_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_LowerLimitPrice_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_PreDelta_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_PreDelta_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_CurrDelta_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_CurrDelta_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_UpdateTime_set(long jarg1, EESMarketDepthQuoteData jarg1_, String jarg2);
  public final static native String EESMarketDepthQuoteData_UpdateTime_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_UpdateMillisec_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_UpdateMillisec_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_BidPrice1_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_BidPrice1_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_BidVolume1_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_BidVolume1_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_AskPrice1_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_AskPrice1_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_AskVolume1_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_AskVolume1_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_BidPrice2_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_BidPrice2_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_BidVolume2_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_BidVolume2_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_AskPrice2_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_AskPrice2_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_AskVolume2_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_AskVolume2_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_BidPrice3_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_BidPrice3_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_BidVolume3_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_BidVolume3_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_AskPrice3_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_AskPrice3_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_AskVolume3_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_AskVolume3_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_BidPrice4_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_BidPrice4_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_BidVolume4_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_BidVolume4_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_AskPrice4_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_AskPrice4_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_AskVolume4_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_AskVolume4_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_BidPrice5_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_BidPrice5_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_BidVolume5_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_BidVolume5_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_AskPrice5_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_AskPrice5_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_AskVolume5_set(long jarg1, EESMarketDepthQuoteData jarg1_, int jarg2);
  public final static native int EESMarketDepthQuoteData_AskVolume5_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native void EESMarketDepthQuoteData_AveragePrice_set(long jarg1, EESMarketDepthQuoteData jarg1_, double jarg2);
  public final static native double EESMarketDepthQuoteData_AveragePrice_get(long jarg1, EESMarketDepthQuoteData jarg1_);
  public final static native long new_EESMarketDepthQuoteData();
  public final static native void delete_EESMarketDepthQuoteData(long jarg1);
  public final static native String EES_QUOTE_DLL_NAME_get();
  public final static native void delete_EESQuoteEvent(long jarg1);
  public final static native void EESQuoteEvent_OnEqsConnected(long jarg1, EESQuoteEvent jarg1_);
  public final static native void EESQuoteEvent_OnEqsConnectedSwigExplicitEESQuoteEvent(long jarg1, EESQuoteEvent jarg1_);
  public final static native void EESQuoteEvent_OnEqsDisconnected(long jarg1, EESQuoteEvent jarg1_);
  public final static native void EESQuoteEvent_OnEqsDisconnectedSwigExplicitEESQuoteEvent(long jarg1, EESQuoteEvent jarg1_);
  public final static native void EESQuoteEvent_OnLoginResponse(long jarg1, EESQuoteEvent jarg1_, boolean jarg2, String jarg3);
  public final static native void EESQuoteEvent_OnLoginResponseSwigExplicitEESQuoteEvent(long jarg1, EESQuoteEvent jarg1_, boolean jarg2, String jarg3);
  public final static native void EESQuoteEvent_OnQuoteUpdated(long jarg1, EESQuoteEvent jarg1_, int jarg2, long jarg3, EESMarketDepthQuoteData jarg3_);
  public final static native void EESQuoteEvent_OnQuoteUpdatedSwigExplicitEESQuoteEvent(long jarg1, EESQuoteEvent jarg1_, int jarg2, long jarg3, EESMarketDepthQuoteData jarg3_);
  public final static native void EESQuoteEvent_OnWriteTextLog(long jarg1, EESQuoteEvent jarg1_, int jarg2, String jarg3, int jarg4);
  public final static native void EESQuoteEvent_OnWriteTextLogSwigExplicitEESQuoteEvent(long jarg1, EESQuoteEvent jarg1_, int jarg2, String jarg3, int jarg4);
  public final static native void EESQuoteEvent_OnSymbolRegisterResponse(long jarg1, EESQuoteEvent jarg1_, int jarg2, String jarg3, boolean jarg4);
  public final static native void EESQuoteEvent_OnSymbolRegisterResponseSwigExplicitEESQuoteEvent(long jarg1, EESQuoteEvent jarg1_, int jarg2, String jarg3, boolean jarg4);
  public final static native void EESQuoteEvent_OnSymbolUnregisterResponse(long jarg1, EESQuoteEvent jarg1_, int jarg2, String jarg3, boolean jarg4);
  public final static native void EESQuoteEvent_OnSymbolUnregisterResponseSwigExplicitEESQuoteEvent(long jarg1, EESQuoteEvent jarg1_, int jarg2, String jarg3, boolean jarg4);
  public final static native void EESQuoteEvent_OnSymbolListResponse(long jarg1, EESQuoteEvent jarg1_, int jarg2, String jarg3, boolean jarg4);
  public final static native void EESQuoteEvent_OnSymbolListResponseSwigExplicitEESQuoteEvent(long jarg1, EESQuoteEvent jarg1_, int jarg2, String jarg3, boolean jarg4);
  public final static native long new_EESQuoteEvent();
  public final static native void EESQuoteEvent_director_connect(EESQuoteEvent obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void EESQuoteEvent_change_ownership(EESQuoteEvent obj, long cptr, boolean take_or_release);
  public final static native void delete_EESQuoteApi(long jarg1);
  public final static native boolean EESQuoteApi_ConnServer__SWIG_0(long jarg1, EESQuoteApi jarg1_, long jarg2, long jarg3, EESQuoteEvent jarg3_);
  public final static native boolean EESQuoteApi_ConnServer__SWIG_1(long jarg1, EESQuoteApi jarg1_, long jarg2, EqsTcpInfo jarg2_, long jarg3, EESQuoteEvent jarg3_);
  public final static native boolean EESQuoteApi_InitMulticast(long jarg1, EESQuoteApi jarg1_, long jarg2, long jarg3, EESQuoteEvent jarg3_);
  public final static native void EESQuoteApi_LoginToEqs(long jarg1, EESQuoteApi jarg1_, long jarg2, EqsLoginParam jarg2_);
  public final static native void EESQuoteApi_QuerySymbolList(long jarg1, EESQuoteApi jarg1_);
  public final static native void EESQuoteApi_RegisterSymbol(long jarg1, EESQuoteApi jarg1_, int jarg2, String jarg3);
  public final static native void EESQuoteApi_UnregisterSymbol(long jarg1, EESQuoteApi jarg1_, int jarg2, String jarg3);
  public final static native void EESQuoteApi_DisConnServer(long jarg1, EESQuoteApi jarg1_);
  public final static native long new_EESQuoteApi();
  public final static native void EESQuoteApi_director_connect(EESQuoteApi obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void EESQuoteApi_change_ownership(EESQuoteApi obj, long cptr, boolean take_or_release);
  public final static native String CREATE_EES_QUOTE_API_NAME_get();
  public final static native String DESTROY_EES_QUOTE_API_NAME_get();

  public static void SwigDirector_EESQuoteEvent_OnEqsConnected(EESQuoteEvent jself) {
    jself.OnEqsConnected();
  }
  public static void SwigDirector_EESQuoteEvent_OnEqsDisconnected(EESQuoteEvent jself) {
    jself.OnEqsDisconnected();
  }
  public static void SwigDirector_EESQuoteEvent_OnLoginResponse(EESQuoteEvent jself, boolean bSuccess, String pReason) {
    jself.OnLoginResponse(bSuccess, pReason);
  }
  public static void SwigDirector_EESQuoteEvent_OnQuoteUpdated(EESQuoteEvent jself, int chInstrumentType, long pDepthQuoteData) {
    jself.OnQuoteUpdated(EesEqsIntrumentType.swigToEnum(chInstrumentType), (pDepthQuoteData == 0) ? null : new EESMarketDepthQuoteData(pDepthQuoteData, false));
  }
  public static void SwigDirector_EESQuoteEvent_OnWriteTextLog(EESQuoteEvent jself, int nlevel, String pLogText, int nLogLen) {
    jself.OnWriteTextLog(EesEqsLogLevel.swigToEnum(nlevel), pLogText, nLogLen);
  }
  public static void SwigDirector_EESQuoteEvent_OnSymbolRegisterResponse(EESQuoteEvent jself, int chInstrumentType, String pSymbol, boolean bSuccess) {
    jself.OnSymbolRegisterResponse(EesEqsIntrumentType.swigToEnum(chInstrumentType), pSymbol, bSuccess);
  }
  public static void SwigDirector_EESQuoteEvent_OnSymbolUnregisterResponse(EESQuoteEvent jself, int chInstrumentType, String pSymbol, boolean bSuccess) {
    jself.OnSymbolUnregisterResponse(EesEqsIntrumentType.swigToEnum(chInstrumentType), pSymbol, bSuccess);
  }
  public static void SwigDirector_EESQuoteEvent_OnSymbolListResponse(EESQuoteEvent jself, int chInstrumentType, String pSymbol, boolean bLast) {
    jself.OnSymbolListResponse(EesEqsIntrumentType.swigToEnum(chInstrumentType), pSymbol, bLast);
  }
  public static boolean SwigDirector_EESQuoteApi_ConnServer__SWIG_0(EESQuoteApi jself, long vecEti, long pQuoteEventHandler) {
    return jself.ConnServer(new SWIGTYPE_p_std__vectorT_EqsTcpInfo_t(vecEti, false), (pQuoteEventHandler == 0) ? null : new EESQuoteEvent(pQuoteEventHandler, false));
  }
  public static boolean SwigDirector_EESQuoteApi_ConnServer__SWIG_1(EESQuoteApi jself, long svrInfo, long pQuoteEventHandler) {
    return jself.ConnServer(new EqsTcpInfo(svrInfo, false), (pQuoteEventHandler == 0) ? null : new EESQuoteEvent(pQuoteEventHandler, false));
  }
  public static boolean SwigDirector_EESQuoteApi_InitMulticast(EESQuoteApi jself, long vecEmi, long pQuoteEventHandler) {
    return jself.InitMulticast(new SWIGTYPE_p_std__vectorT_EqsMulticastInfo_t(vecEmi, false), (pQuoteEventHandler == 0) ? null : new EESQuoteEvent(pQuoteEventHandler, false));
  }
  public static void SwigDirector_EESQuoteApi_LoginToEqs(EESQuoteApi jself, long loginParam) {
    jself.LoginToEqs(new EqsLoginParam(loginParam, false));
  }
  public static void SwigDirector_EESQuoteApi_QuerySymbolList(EESQuoteApi jself) {
    jself.QuerySymbolList();
  }
  public static void SwigDirector_EESQuoteApi_RegisterSymbol(EESQuoteApi jself, int chInstrumentType, String pSymbol) {
    jself.RegisterSymbol(EesEqsIntrumentType.swigToEnum(chInstrumentType), pSymbol);
  }
  public static void SwigDirector_EESQuoteApi_UnregisterSymbol(EESQuoteApi jself, int chInstrumentType, String pSymbol) {
    jself.UnregisterSymbol(EesEqsIntrumentType.swigToEnum(chInstrumentType), pSymbol);
  }
  public static void SwigDirector_EESQuoteApi_DisConnServer(EESQuoteApi jself) {
    jself.DisConnServer();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
